/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

const Header = () => {
  return (
    <header className={styles.header}>
      <h1 className={styles.logo}>App Logo/Name</h1>
      <nav className={styles.nav}>
        <a href="/" className={styles.navItem}>
          Home
        </a>
        <a href="/profile" className={styles.navItem}>
          Profile
        </a>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/769b094b26beb55d89d24b2094910d4e9bcd6e8c96a110e8ccf506e3769bf6e1?apiKey=f26241707f634688924ec6932fe814fb&"
          alt="Profile"
          className={styles.profileIcon}
        />
      </nav>
    </header>
  );
};

export default Header;
