/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../Header/Header";
import ProductGrid from "../ProductGrid/ProductGrid";
import styles from "./BestSelling.module.css";

const BestSelling = () => {
  return (
    <main className={styles.container}>
      <Header />
      <h2 className={styles.title}>Best Selling Products</h2>
      <ProductGrid />
      <button className={styles.loadMoreButton}>Load More</button>
    </main>
  );
};

export default BestSelling;
