/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProductCard from "../ProductCard/ProductCard";
import styles from "./ProductGrid.module.css";

const productData = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/2aab0df5536d48e1dac8213fef49108bda4270254f718b42d1f6331a7f0aa517?apiKey=f26241707f634688924ec6932fe814fb&",
    rating: "4.2",
    reviewCount: "659",
    brand: "Louis Philippe",
    description: "Lightly Washed Slim Fit Jeans",
    currentPrice: "999",
    originalPrice: "1999",
    discount: "50",
  },
  // Repeat this object 5 more times for a total of 6 products
  // ... (omitted for brevity)
];

const ProductGrid = () => {
  return (
    <section className={styles.productGrid}>
      {productData.map((product, index) => (
        <div key={index} className={styles.productColumn}>
          <ProductCard {...product} />
        </div>
      ))}
    </section>
  );
};

export default ProductGrid;
