/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ProductCard.module.css";

const ProductCard = ({
  image,
  rating,
  reviewCount,
  brand,
  description,
  currentPrice,
  originalPrice,
  discount,
}) => {
  return (
    <article className={styles.productCard}>
      <div className={styles.imageWrapper}>
        <img
          src={image}
          alt={`${brand} ${description}`}
          className={styles.productImage}
        />
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6e6a4565622fc6c6a84111dcaaf96a110a158e8f4a0166870ef072d026fc0eb9?apiKey=f26241707f634688924ec6932fe814fb&"
          alt=""
          className={styles.wishlistIcon}
        />
        <div className={styles.ratingWrapper}>
          <div className={styles.ratingContent}>
            <span className={styles.ratingValue}>{rating}</span>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/4b0296d64a74783c8bf7fd24a8c1be8f44f4fb23a737177d58b39c40708a929b?apiKey=f26241707f634688924ec6932fe814fb&"
              alt="Star rating"
              className={styles.starIcon}
            />
          </div>
          <div className={styles.reviewCount}>
            <span className={styles.separator}>|</span>
            <span className={styles.count}>{reviewCount}</span>
          </div>
        </div>
      </div>
      <div className={styles.productInfo}>
        <h3 className={styles.brand}>{brand}</h3>
        <p className={styles.description}>{description}</p>
        <div className={styles.priceWrapper}>
          <div className={styles.priceInfo}>
            <span className={styles.currentPrice}>Rs. {currentPrice}</span>
            <span className={styles.originalPrice}>Rs. {originalPrice}</span>
          </div>
          <span className={styles.discount}>({discount}% OFF)</span>
        </div>
      </div>
    </article>
  );
};

export default ProductCard;
